### PR TITLE
Changed Artillery Logo URL. Fixes #39

### LINKED ISSUE #39: artillery-service 0.3.1 logo image: error downloading and saving logo image
We are receiving the following error on artifacthub:
```
error preparing package artillery-service version 0.3.1 logo image: error downloading and saving logo image: unexpected status code received: 404
```

Seems like the artillery service logo is missing?

### PR DESCRIPTION
**Pull request by TannerGilbert**

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
The new URL does not exist

**Comment by TannerGilbert** [comment]
> The new URL does not exist

@oleg-nenashev `https://camo.githubusercontent.com/1af5bda8458e6a9a237a4d78a0b05826c3c04a9625ac4e3d1ac12aa0c75b327c/68747470733a2f2f617274696c6c6572792e696f2f696d616765732f617274696c6c6572792d6c6f676f2d7371756172652e706e67` seems to work for me.

**Comment by TannerGilbert** [comment]
@oleg-nenashev seems like they removed the logo from the first commit as well. I just downloaded the logo as a svg and saved it inside the images directory. Should work now.

**Review by oleg-nenashev — APPROVED** [review]
Thank you! Indeed we should avoid external dependencies as much as possible

**Pull request merged**
