### PR TITLE
Zapier Integration: Fix Image Links

### PR DESCRIPTION
**Pull request by ghost**
Fix image links for Zapier integration.

### CODE REVIEW

**Comment by christian-kreuzberger-dtx** [comment]
Hi Adam, your PR has conflicts with the files you are trying to modify:
image

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Merge conflict needs to be resolved before wee proceed

**Review by TannerGilbert — APPROVED** [review]
Thanks for fixing the merge conflict. The changes should fix the displaying problems.

**Review by oleg-nenashev — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
This is a right fix. Not sure why Linter is unhappy, restarting

**Comment by oleg-nenashev** [comment]
image

**Comment by TannerGilbert** [comment]
@oleg-nenashev There is already an issue regarding the linting error: https://github.com/keptn-contrib/artifacthub/issues/89

**Comment by christian-kreuzberger-dtx** [comment]
can we get this merged please (there is now another conflict, beacuse it wasn't merged yet...).

as already detailed in the related GH issue, as long as the linter succeeds, we can merge it.
image

**Review by jetzlstorfer — APPROVED** [review]

**Review by TannerGilbert — APPROVED** [review]
LGTM

**Pull request merged**
